---
apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: quarkus-crud
  labels:
    app: quarkus-crud
    environment: production
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
# stringData:
#   QUARKUS_DATASOURCE_USERNAME: postgres
#   QUARKUS_DATASOURCE_PASSWORD: postgres
# 他にも秘密にしたい環境変数をここに追加可能
