---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: quarkus-crud-db
  namespace: quarkus-crud
  labels:
    app: quarkus-crud
    component: database
    name: quarkus-crud-db
spec:
  name: quarkus_crud
  owner: quarkus-crud
  cluster:
    name: pg-cluster
