apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus-crud

resources:
  - backend.yaml
  - common-secret.yaml
  - jwt-keys.yaml
  - ingress.yaml

configMapGenerator:
  - name: backend-config
    files:
      - application.properties

images:
  - name: ghcr.io/yuki-js/quarkus-crud
    newTag: latest-native

labels:
  - pairs:
      app: quarkus-crud
